{
  "sksl": {
    "entrypoint": "progressive_blur_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 child_size;\nuniform float blur_sigma;\nuniform float blur_direction;\nuniform vec4 tint_color;\nuniform shader child_texture;\nuniform half2 child_texture_size;\nuniform shader blur_texture;\nuniform half2 blur_texture_size;\n\nvec4 frag_color;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_main()\n{\n    vec2 uv = FLT_flutter_local_FlutterFragCoord() / child_size;\n    float blur_value = pow(blur_texture.eval(blur_texture_size * ( uv)).x, 2.0);\n    float sigma = blur_sigma * blur_value;\n    bvec2 _57 = bvec2(blur_direction == 0.0);\n    vec2 dir = vec2(_57.x ? vec2(1.0, 0.0).x : vec2(0.0, 1.0).x, _57.y ? vec2(1.0, 0.0).y : vec2(0.0, 1.0).y);\n    if (sigma < 9.9999997473787516355514526367188e-06)\n    {\n        frag_color = child_texture.eval(child_texture_size * ( uv));\n        return;\n    }\n    int kernel_radius = int(ceil(3.0 * sigma));\n    int kernel_size = (2 * kernel_radius) + 1;\n    if (kernel_size > 255)\n    {\n        kernel_radius = 127;\n        kernel_size = 255;\n    }\n    float total_weight = 0.0;\n    vec4 color = vec4(0.0);\n    for (int i = 0; i < 255; i++)\n    {\n        if (i >= kernel_size)\n        {\n            break;\n        }\n        int v = i - kernel_radius;\n        float weight = exp((-float(v * v)) / ((2.0 * sigma) * sigma));\n        total_weight += weight;\n        vec2 offset = vec2(float(v)) / child_size;\n        offset *= dir;\n        color += (child_texture.eval(child_texture_size * ( uv + offset)) * weight);\n    }\n    vec4 blurred = color / vec4(total_weight);\n    float tint_strength = blur_value * tint_color.w;\n    frag_color = mix(blurred, tint_color, vec4(tint_strength));\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return frag_color;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 0,
        "columns": 1,
        "location": 0,
        "name": "child_texture",
        "rows": 1,
        "type": 12
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "child_size",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 0,
        "columns": 1,
        "location": 2,
        "name": "blur_texture",
        "rows": 1,
        "type": 12
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 3,
        "name": "blur_sigma",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 4,
        "name": "blur_direction",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 5,
        "name": "tint_color",
        "rows": 4,
        "type": 10
      }
    ]
  }
}